apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-docker
spec:
  selector:
    deploymentconfig: simple-webapp-docker             #Deployment config label from openshift Service GUI
  clusterIP: 172.30.136.123                          #it can be assigned automatically
  ports:
    name: 8080-tcp
    port: 8080
    protocol: TCP
    targetport: 8080
